<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>


        <?php  
            $helper =  $block->getGalleryImagesJson();
            $arr=json_decode($helper);
            $imageCount=( count($arr));
            if ($imageCount <= 1){
                foreach ($arr as $key=>$value) {
        ?>     
                <img itemprop="image" title="<?= $value->caption ?>" id="productimg"  width="700" height="700" src="<?= $value->img ?>" >

<?php    }  }else { ?>

<div id="mytekmobile" class="carousel slide block-carrousel" data-interval="false" data-ride="carousel" data-touch="true">        
    <div class="carousel-inner">
        <?php  
            $helper =  $block->getGalleryImagesJson();
            $arr=json_decode($helper);
            foreach ($arr as $key=>$value) {
                if ($key==0){
            ?>
            <div class="carousel-item active">
                <?php  }else { ?>
                        <div class="carousel-item ">
                <?php  }?>
                <img itemprop="image" title="<?= $value->caption ?>" id="productimg"  width="700" height="700" src="<?= $value->img ?>" >
                
            </div>
        <?php  }   ?> 
    </div>
    <a class="carousel-control-prev" role="button" href="#mytekmobile" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" role="button" href="#mytekmobile" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
     <!-- Thumbnails -->
     <ol class="carousel-indicators list-inline">

        <?php  
            $helper =  $block->getGalleryImagesJson();
            $arr=json_decode($helper);
            foreach ($arr as $key=>$value) {
                if ($key==0){
            ?>
                <li class="list-inline-item active">
                    <a id="carousel-selector-<?= $key ?>" class="selected" data-slide-to="<?= $key ?>" data-target="#mytekmobile">
                    <img width="700" height="700" src="<?= $value->img ?>" title="<?= $value->caption ?>" class="img-fluid">
                    </a>
                </li>
                <?php  }else { ?>
                    <li class="list-inline-item">
                        <a id="carousel-selector-<?= $key ?>" data-slide-to="<?= $key ?>" data-target="#mytekmobile">
                        <img src="<?= $value->img ?>" width="700" height="700" title="<?= $value->caption ?>" class="img-fluid">
                        </a>
                    </li>   
                <?php  }?>
        <?php  }   ?>
    </ol>
</div>
<?php  } ?>
<style>

.block-carrousel{
    margin-bottom:110px;
}
.carousel-inner img {
      width: 100%;
      height: 100%;
  }

#mytekmobile .carousel-indicators {
    position: static;
    margin-bottom: 30px;
}

#mytekmobile .carousel-indicators > li {
  width:30%;
}

 #mytekmobile .carousel-indicators li img {
    display: block;
    opacity: 0.5;
 }

  #mytekmobile .carousel-indicators li.active img {
    opacity: 1;
    border: 1px solid #ff5501;
  }

  #mytekmobile .carousel-indicators li:hover img {
    opacity: 0.75;
  }

  .carousel-item img{
    width:100%;
  }

  .carousel-indicators li{
      background-color:inherit !important;
      height: 0px !important;
  }
  .carousel-control-next:hover,.carousel-control-prev:hover{
    background: rgba(213,213,213,.2);
  }
  .carousel-control-next-icon, .carousel-control-prev-icon{
    width: 30px;
    height: 30px;
  }
</style>
