<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Customer\Block\Account\Customer $block */
?>
<?php if ($block->customerLoggedIn()) : ?>
    <li onmouseover="displayy()" onmouseout="displayNo()" class="customer-welcome">
       <span class="dashboard">
            <?php echo __("My Account") ?>
        </span>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
        <?php if ($block->getChildHtml()) :?>
            <div class="customer-menu" data-target="dropdown">
                <?= $block->getChildHtml() ?>
            </div>
        <?php endif; ?>
    </li>
<?php endif; ?>
<script type="text/javascript">
    function displayy() {
        
        document.getElementsByClassName("customer-menu")[0].style.display ="block";
                
    }
    function displayNo() {
        
        document.getElementsByClassName("customer-menu")[0].style.display ="none";
                
    }
</script>
