<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
	   $_productCollection = $block->getLoadedProductCollection();
	   /** @var \Magento\Catalog\Helper\Output $_helper */
	   $_helper = $block->getData('outputHelper');
	   ?>
	<?php if (!$_productCollection->count()): ?>
	<div class="message info empty">
	   <div><?php
	      $url=$_SERVER['REQUEST_URI'];
	      //var_dump($url);  
	    if(!str_contains($url,"catalogsearch/result/")) {
		 exit(1);die('Categorie vide');
	    }else{
	      $escaper->escapeHtml(__('We can\'t find products matching the selection.'));
	      
	    }
	    ?></div>
	</div>
	<?php else: ?>
	<?= $block->getToolbarHtml() ?>
	<?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <script type="application/ld+json">
 
 {
 "@context": "http://schema.org/",
 "@type": "Product",
 "name": "<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>",
 "description" : " <?php
 
         $test= strip_tags($_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description'));
         $p= str_replace('"',' ',$test);
         echo $p;
      ?>",
 "image":"<?php echo $productImageUrl = $block->getUrl('pub/media/catalog').'product'.$_product->getImage(); ?>",
 "url": "<?php echo $_product->getProductUrl(); ?>",
 "sku": "<?php echo $_product->getSku(); ?>",
 "gtin13":"<?php echo $_product->getGtin(); ?>",
 "brand": {
         "@type":"Brand",
         "name":"<?php echo $_product->getAttributeText('manufacturer') ?>"
     }, 
 
 "review": <?php if($_product->getRatingSummary()){ ?>
         {
           "@type":"Review",
           "reviewRating": {
             "@type": "Rating",
             "ratingValue": " <?php echo $_product->getRatingSummary(); ?>",
             "worstRating":"0",
             "bestRating": "100"
           },
           "author": {
             "@type": "Person",
             "name": "<?php echo "name"; ?>"
               }
         },
         "aggregateRating": {
           "@type": "AggregateRating",
           "ratingValue": "<?php echo $_product->getRatingSummary(); ?>",
           "worstRating":"0",
             "bestRating": "100",
           "reviewCount": "<?php echo $_product->getReviewsCount(); ?>"
         }
 <?php } else
 echo "\" \" ";
  ?>,
 "availability":" <?php $_stock_status = $_product->getAttributeText('erpstock'); ?>
                      <?php echo $_stock_status; ?>",
 "offers": {
         "@type": "Offer",
         "url": "<?php echo $_product->getProductUrl(); ?>",
         "priceCurrency": "TND",
         "price": "<?php echo $_product->getFinalPrice(); ?>",
         "priceValidUntil": "<?php echo date("Y-12-31");?>",
         "itemCondition": "https://schema.org/UsedCondition",
         "availability": "
             <?php
                     if ($_stock_status === "Sur commande 48h")
 
                     echo "https://schema.org/PreOrder";
                     elseif ($_stock_status === "En arrivage")
              
                     echo "https://schema.org/BackOrder";
                     elseif ($_stock_status === "En stock")
                     echo " https://schema.org/InStock";
                     else
                     echo 'https://schema.org/OutOfStock';
 
                 ?>"
 
       }
 
 }
 </script>
                <table> 
                    <tr class="item product product-item product-item-info" >
                        <td style="display: block; padding:0 8px" class="mobileNameProduct">
                                                <div class=" product details product-item-details " onclick="location.href='<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>'">
                                                    <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                                    <strong class="product name product-item-name ">
                                                        <a class="product-item-link" href="<?= /* @escapeNotVerified */
                                                                $_product->getProductUrl() ?>">
                                                            <?= /* @escapeNotVerified */
                                                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                                        </a>
                                                    </strong>
                                                </div>
                        </td>
                        <td class="col-lg-2 col-sm-2 col-md-2 col-xs-2 padingRight" style="width: 150px !important" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                                                <div class=" image-product">
                                                    <?php
                                                    $productImage = $block->getImage($_product, $imageDisplayArea);
                                                    if ($pos != null) {
                                                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                                            . 'top:' . $productImage->getHeight() . 'px;"';
                                                    }
                                                    ?>
                                                    <?php // Product Image ?>
                                                    <a href="<?= /* @escapeNotVerified */
                                                                                $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                                                        tabindex="-1">
                                                        <?= $productImage->toHtml() ?>
                                                    </a>
                                                </div>
                                                <div class="dipRate">
                                                    <div class="dispoMobile">
                                                        <!--start en stock-->
                                                        <fieldset class="dispo mt-2">
                                                            <legend class="disponibilite"> Disponibilité</legend>
                                                            <?php if ($block->displayProductStockStatus()) :?>
                                                    <?php $_stock_status = $_product->getAttributeText('erpstock'); ?>
                                                  
                                                   
                                                        <?php if ($_stock_status === "Sur commande 48h") :?>
                                                            <div class="stock available unavailable_preorder" title="<?php echo $_stock_status; ?>">
                                                                <span><?php echo $_stock_status; ?>                                                          
                                                            </span>
                                                            </div>
                                                        <?php elseif ($_stock_status === "En arrivage") :?>
                                                            <div class="stock available available_backorder" title="<?php echo $_stock_status; ?>">
                                                                <span><?php echo $_stock_status; ?></span>
                                                            </div>
                                                        <?php elseif ($_stock_status === "En stock") :?>
                                                            <div class="stock available"  title="<?php echo $_stock_status; ?>">
                                                                <span><?php echo $_stock_status; ?></span>
                                                            </div>
                                                        
                                                        <?php else :?>
                                                        <div class="stock unavailable" title="<?php echo $_stock_status; ?>">
                                                            <span><?php echo $_stock_status; ?></span>
                                                        </div>
                                                        <?php endif; ?>
                                                <?php endif; ?>
                                                        </fieldset>                                        
                                                        <!--end en stock-->
                                                    </div>
                                                            <div class="mobileWidth">
                                                                        <div class="ListReview ReviewMobile">
                                                                        <?= $this->getReviewsSummaryHtml($_product, 'short') ?>
                                                                        
                                                                        </div>
                                                            </div>
                                                    <div class="product-item-inner panierMobile">
                                                        <div class="product actions product-item-actions">
                                                            <div class="actions-primary">
                                                                <?php if ($_product->isSaleable()): ?>
                                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                                <form data-role="tocart-form"
                                                                    data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                                    action="<?= /* @NoEscape */
                                                                                    $postParams['action'] ?>" method="post">
                                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */
                                                                                        $postParams['data']['product'] ?>">
                                                                    <input type="hidden" name="<?= /* @escapeNotVerified */
                                                                                    Action::PARAM_NAME_URL_ENCODED ?>"
                                                                        value="<?= /* @escapeNotVerified */
                                                                                        $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                    <?= $block->getBlockHtml('formkey') ?>
                                                                    <?php $_stock_status = $_product->getAttributeText('erpstock'); ?>
                                                                    <?php if ( $_stock_status === "Epuisé") :?>
                                                                        <button type="submit"
                                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                            class="action disabled tocart primary">
                                                                            <span>
                                                                                <?= /* @escapeNotVerified */
                                                                                            __('Add to Cart') ?>
                                                                            </span>
                                                                        </button>
                                                                    <?php else: ?>
                                                                        <button type="submit"
                                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                            class="action  tocart primary">
                                                                            <span>
                                                                                <?= /* @escapeNotVerified */
                                                                                            __('Add to Cart') ?>
                                                                            </span>
                                                                        </button>
                                                                    <?php endif; ?>

                                                                </form>
                                                                <?php else: ?>
                                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                                <form data-role="tocart-form"
                                                                    data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                                    action="<?= /* @NoEscape */
                                                                                    $postParams['action'] ?>" method="post">
                                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */
                                                                                        $postParams['data']['product'] ?>">
                                                                    <input type="hidden" name="<?= /* @escapeNotVerified */
                                                                                    Action::PARAM_NAME_URL_ENCODED ?>"
                                                                        value="<?= /* @escapeNotVerified */
                                                                                        $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                    <?= $block->getBlockHtml('formkey') ?>
                                                                    <button type="submit"
                                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                        class="action disabled tocart primary">
                                                                        <span>
                                                                            <?= /* @escapeNotVerified */
                                                                                        __('Add to Cart') ?>
                                                                        </span>
                                                                    </button>
                                                                </form>
                                                                <?php endif; ?>
                                                            </div>
                                                            <div data-role="add-to-links" class="actions-secondary">
                                                                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                                                <?php endif; ?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                        </td>
                        <td class="col-lg-9 col-sm-7 col-md-7 col-xs-7 padingLeft">
                            <div class="product details product-item-details" onclick="location.href='<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>'" >
                                    <div class="desctopNameProduct">
                                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                        <strong class="product name product-item-name ">
                                            <a class="product-item-link" href="<?= /* @escapeNotVerified */
                                                    $_product->getProductUrl() ?>">
                                                <?= /* @escapeNotVerified */
                                                        $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                            </a>
                                        </strong>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-4 col-md-4 col-sm-4 mobileWidth">
                                            <div class="skuDesktop">
                                                [<?php /* @escapeNotVerified */ echo $_product->getSku() ?>]
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-4 col-sm-4 mobileWidth">
                                            <div class="ListReview Reviewdesktop">
                                            <?php echo $this->getReviewsSummaryHtml($_product, 'short'); ?>

                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-4 col-sm-4 mobileWidth">
                                            <div class="brand">
                                            <!-- manufacturer  -->
                                                <?php                  
                                                    $brand=strtolower ($_product->getAttributeText('manufacturer'));
    if ($brand != "" && $brand != "sans fabricant") {
        echo '<a href="'.$block->getBaseUrl().str_replace(' ', '_',$brand).'"><img style="width:32%;height:30%;display:block;" src="https://media.mytek.tn/media/wysiwyg/marque/'.str_replace(' ', '_',$brand).'.jpg" alt="'.$brand.'"></a>' ;
    }
                                                ?>
                                            <!-- --------- -->
                                            </div>
                                        </div>
                                    </div>
                                   
                                    <div class="brand-img brandMobile">
                                        <?= $block->getProductDetailsHtml($_product) ?>
                                    </div>
                                    <div class="priceMobile">
                                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                                    </div>
                                    <div class="skuMobile">
                                        [<?php /* @escapeNotVerified */ echo $_product->getSku() ?>]
                                    </div>
                                    
                                    
                                    
                                    <?php if ($showDescription): ?>
                                    <div  class="product description ">                                
                                        <?php /* @escapeNotVerified */                                      
                                         if($_product->getShortDescription()==NULL){
                                            $desc=$_product->getShortDescription();
                                                 echo "<div class='strigDesc'>".$desc."</div>";   
                                        }else{
                                             $desc= strip_tags($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'),'<span>') ;  
                                                  echo "<div class='strigDesc'>".$desc."</div>";   
                                         }                                          
                                        ?>                                                                                                             
                                    </div>
                                    
                                    
                            </div>
                        </td>
                        <td class="col">
                            <div class="mobileNone">
                                <div class="row align-items-center marginclass displayDesctop">                                       
                                <?php endif; ?> 
                                    <div class="mobileWidthLeft">
                                        <div class="brand-img brandDesctop">
                                            <?= $block->getProductDetailsHtml($_product) ?>
                                        </div>
                                        <div class="dispoDesc">
                                            <!--start en stock-->
                                            <fieldset class="dispo mt-2">
                                                <legend class="disponibilite"> Disponibilité</legend>
                                                
                                                <?php if ($block->displayProductStockStatus()) :?>
                                                    <?php $_stock_status = $_product->getAttributeText('erpstock'); ?>
                                                  
                                                   
                                                        <?php if ($_stock_status === "Sur commande 48h") :?>
                                                            <div class="stock available unavailable_preorder" title="<?php echo $_stock_status; ?>">
                                                                <span><?php echo $_stock_status; ?>                                                          
                                                            </span>
                                                            </div>
                                                        <?php elseif ($_stock_status === "En arrivage") :?>
                                                            <div class="stock available available_backorder" title="<?php echo $_stock_status; ?>">
                                                                <span><?php echo $_stock_status; ?></span>
                                                            </div>
                                                        <?php elseif ($_stock_status === "En stock") :?>
                                                            <div class="stock available"  title="<?php echo $_stock_status; ?>">
                                                                <span><?php echo $_stock_status; ?></span>
                                                            </div>
                                                        
                                                        <?php else :?>
                                                        <div class="stock unavailable" title="<?php echo $_stock_status; ?>">
                                                            <span><?php echo $_stock_status; ?></span>
                                                        </div>
                                                        <?php endif; ?>
                                                <?php endif; ?>
                                            </fieldset>                                        
                                            
                                            <!--end en stock-->
                                        </div>
                                        <div class="priceDesctop">
                                            <?= /* @escapeNotVerified */    $block->getProductPrice($_product) ?>
                                        </div>
                                    
                                        <div class="product-item-inner panierDesc">
                                                <div class="product actions product-item-actions">
                                                    <div class="actions-primary">
                                                        <?php if ($_product->isSaleable()): ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form"
                                                            data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                            action="<?= /* @NoEscape */
                                                                            $postParams['action'] ?>" method="post">
                                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */
                                                                                $postParams['data']['product'] ?>">
                                                            <input type="hidden" name="<?= /* @escapeNotVerified */
                                                                            Action::PARAM_NAME_URL_ENCODED ?>"
                                                                value="<?= /* @escapeNotVerified */
                                                                                $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <?php $_stock_status = $_product->getAttributeText('erpstock'); ?>
                                                            <?php if ( $_stock_status === "En arrivage") :?>
                                                                <button type="submit"
                                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                    class="action disabled tocart primary">
                                                                    <span>
                                                                        <?= /* @escapeNotVerified */
                                                                                    __('Add to Cart') ?>
                                                                    </span>
                                                                </button>
                                                            <?php else: ?>
                                                                <button type="submit"
                                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                    class="action  tocart primary">
                                                                    <span>
                                                                        <?= /* @escapeNotVerified */
                                                                                    __('Add to Cart') ?>
                                                                    </span>
                                                                </button>
                                                            <?php endif; ?>
                                                        </form>
                                                        <?php else: ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form" 
                                                        data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" 
                                                        action="<?= /* @NoEscape */ 
                                                        $postParams['action'] ?>" method="post">
                                                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */
                                                                                                    $postParams['data']['product'] ?>">
                                                                                <input type="hidden" name="<?= /* @escapeNotVerified */
                                                                                                Action::PARAM_NAME_URL_ENCODED ?>"
                                                                                    value="<?= /* @escapeNotVerified */
                                                                                                    $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                                    class="action disabled tocart primary">
                                                                                    <span>
                                                                                        <?= /* @escapeNotVerified */
                                                                                                    __('Add to Cart') ?>
                                                                                    </span>
                                                            </button>
                                                        </form>
                                                        <?php endif; ?>
                                                    </div>
                                                    <div data-role="add-to-links" class="actions-secondary">
                                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                        </td>
                    </tr>   
                </table>
                
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
            }
        }
    }
    </script>
<?php endif; ?>
